# finetune_config.yaml

# 1) Dữ liệu & feature
data:
  # Thư mục chứa các file manifest JSON do DataConfig yêu cầu
  manifest_dir: ./cache_train
  sample_rate: 16000
  num_mel_bins: 80
  frame_length: 25      # in ms
  frame_shift: 10       # in ms
  dither: 0.0
  energy_floor: 0.0

# 2) Tokenizer / vocab
tokenizer:
  vocab_path: ../../../chunkformer-large-vie/vocab.txt

# 3) Mô hình
model:
  # Thư mục (hoặc checkpoint file) để load weights
  checkpoint: ../../../chunkformer-large-vie
  # Cân số giữa CTC và AED loss
  ctc_weight: 0.3

# 4) Training hyper-params
training:
  batch_size: 4
  lr: 1e-4
  weight_decay: 0.01
  warmup_steps: 1000
  epochs: 10
  max_grad_norm: 5.0
  log_steps: 50
  checkpoint_dir: checkpoints

# 5) Chunking parameters (cho forward chunked encoder)
chunk:
  chunk_size: 64
  left_context_size: 128
  right_context_size: 128
  total_batch_duration: 1800  # ms
